[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
startCommand = "node scripts/migrate.js && node dist/main.js"
healthcheckPath = "/api/v1/health/ready"
healthcheckTimeout = 100

[env]
NODE_ENV = "production"
PORT = "3000"
CORS_ORIGINS = "https://matboss.online"
SMTP_HOST = "localhost"
